TERMUX_PKG_HOMEPAGE=https://herbstluftwm.org
TERMUX_PKG_DESCRIPTION="A manual tiling window manager for X11"
TERMUX_PKG_LICENSE="BSD Simplified"
TERMUX_PKG_MAINTAINER="@leapofazzam123"
TERMUX_PKG_VERSION=0.9.3
TERMUX_PKG_REVISION=6
TERMUX_PKG_SRCURL=https://herbstluftwm.org/tarballs/herbstluftwm-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0ba7b1bd02966e6eefe27805753082406a2d2954bc41fe040d1ccaaed25ec105
TERMUX_PKG_DEPENDS="libx11, libxrandr, libxinerama, libxext, libxft, freetype"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DCMAKE_INSTALL_SYSCONF_PREFIX=$PREFIX/etc"
